const fundReferenceSeedData=[
  {
    fundName: "HDFC Top 100 Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "HDFC",
    benchmark: "NIFTY 100",
    popularityRank: 1,
  },
  {
    fundName: "SBI Bluechip Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "SBI",
    benchmark: "NIFTY 100",
    popularityRank: 2,
  },
  {
    fundName: "ICICI Prudential Bluechip Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "ICICI",
    benchmark: "NIFTY 100",
    popularityRank: 3,
  },
  {
    fundName: "Axis Bluechip Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "Axis",
    benchmark: "NIFTY 100",
    popularityRank: 4,
  },
  {
    fundName: "Mirae Asset Large Cap Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "Mirae Asset",
    benchmark: "NIFTY 100",
    popularityRank: 5,
  },
  {
    fundName: "Kotak Bluechip Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "Kotak",
    benchmark: "NIFTY 100",
    popularityRank: 6,
  },
  {
    fundName: "UTI Nifty 50 Index Fund",
    assetType: "Equity",
    category: "Index",
    amc: "UTI",
    benchmark: "NIFTY 50",
    popularityRank: 7,
  },
  {
    fundName: "ICICI Prudential Nifty 50 Index Fund",
    assetType: "Equity",
    category: "Index",
    amc: "ICICI",
    benchmark: "NIFTY 50",
    popularityRank: 8,
  },
  {
    fundName: "HDFC Index Fund Nifty 50",
    assetType: "Equity",
    category: "Index",
    amc: "HDFC",
    benchmark: "NIFTY 50",
    popularityRank: 9,
  },
  {
    fundName: "SBI Nifty Index Fund",
    assetType: "Equity",
    category: "Index",
    amc: "SBI",
    benchmark: "NIFTY 50",
    popularityRank: 10,
  },
  {
    fundName: "Canara Robeco Bluechip Equity Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "Canara Robeco",
    benchmark: "NIFTY 100",
    popularityRank: 11,
  },
  {
    fundName: "DSP Top 100 Equity Fund",
    assetType: "Equity",
    category: "Large Cap",
    amc: "DSP",
    benchmark: "NIFTY 100",
    popularityRank: 12,
  },

  {
    fundName: "Axis Midcap Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "Axis",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 13,
  },
  {
    fundName: "Kotak Emerging Equity Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "Kotak",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 14,
  },
  {
    fundName: "HDFC Mid-Cap Opportunities Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "HDFC",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 15,
  },
  {
    fundName: "SBI Magnum Midcap Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "SBI",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 16,
  },
  {
    fundName: "Mirae Asset Midcap Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "Mirae Asset",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 17,
  },
  {
    fundName: "Nippon India Growth Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "Nippon",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 18,
  },
  {
    fundName: "PGIM India Midcap Opportunities Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "PGIM",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 19,
  },
  {
    fundName: "Edelweiss Mid Cap Fund",
    assetType: "Equity",
    category: "Mid Cap",
    amc: "Edelweiss",
    benchmark: "NIFTY Midcap 150",
    popularityRank: 20,
  },

  {
    fundName: "SBI Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "SBI",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 21,
  },
  {
    fundName: "Nippon India Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "Nippon",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 22,
  },
  {
    fundName: "HDFC Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "HDFC",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 23,
  },
  {
    fundName: "Axis Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "Axis",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 24,
  },
  {
    fundName: "Kotak Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "Kotak",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 25,
  },
  {
    fundName: "DSP Small Cap Fund",
    assetType: "Equity",
    category: "Small Cap",
    amc: "DSP",
    benchmark: "NIFTY Smallcap 250",
    popularityRank: 26,
  },

  {
    fundName: "Parag Parikh Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "PPFAS",
    benchmark: "NIFTY 500",
    popularityRank: 27,
  },
  {
    fundName: "Kotak Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "Kotak",
    benchmark: "NIFTY 500",
    popularityRank: 28,
  },
  {
    fundName: "HDFC Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "HDFC",
    benchmark: "NIFTY 500",
    popularityRank: 29,
  },
  {
    fundName: "ICICI Prudential Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "ICICI",
    benchmark: "NIFTY 500",
    popularityRank: 30,
  },
  {
    fundName: "Canara Robeco Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "Canara Robeco",
    benchmark: "NIFTY 500",
    popularityRank: 31,
  },
  {
    fundName: "JM Flexi Cap Fund",
    assetType: "Equity",
    category: "Flexi Cap",
    amc: "JM Financial",
    benchmark: "NIFTY 500",
    popularityRank: 32,
  },

  {
    fundName: "ICICI Prudential Balanced Advantage Fund",
    assetType: "Hybrid",
    category: "Hybrid",
    amc: "ICICI",
    benchmark: "CRISIL Hybrid Index",
    popularityRank: 33,
  },
  {
    fundName: "HDFC Balanced Advantage Fund",
    assetType: "Hybrid",
    category: "Hybrid",
    amc: "HDFC",
    benchmark: "CRISIL Hybrid Index",
    popularityRank: 34,
  },
  {
    fundName: "Kotak Equity Hybrid Fund",
    assetType: "Hybrid",
    category: "Hybrid",
    amc: "Kotak",
    benchmark: "CRISIL Hybrid Index",
    popularityRank: 35,
  },
  {
    fundName: "SBI Equity Hybrid Fund",
    assetType: "Hybrid",
    category: "Hybrid",
    amc: "SBI",
    benchmark: "CRISIL Hybrid Index",
    popularityRank: 36,
  },
  {
    fundName: "Axis Equity Hybrid Fund",
    assetType: "Hybrid",
    category: "Hybrid",
    amc: "Axis",
    benchmark: "CRISIL Hybrid Index",
    popularityRank: 37,
  },

  {
    fundName: "HDFC Corporate Bond Fund",
    assetType: "Debt",
    category: "Corporate Bond",
    amc: "HDFC",
    benchmark: "CRISIL Corporate Bond Index",
    popularityRank: 38,
  },
  {
    fundName: "ICICI Prudential Corporate Bond Fund",
    assetType: "Debt",
    category: "Corporate Bond",
    amc: "ICICI",
    benchmark: "CRISIL Corporate Bond Index",
    popularityRank: 39,
  },
  {
    fundName: "SBI Corporate Bond Fund",
    assetType: "Debt",
    category: "Corporate Bond",
    amc: "SBI",
    benchmark: "CRISIL Corporate Bond Index",
    popularityRank: 40,
  },
  {
    fundName: "Axis Short Term Fund",
    assetType: "Debt",
    category: "Short Duration",
    amc: "Axis",
    benchmark: "CRISIL Short Duration Index",
    popularityRank: 41,
  },
  {
    fundName: "ICICI Prudential Short Term Fund",
    assetType: "Debt",
    category: "Short Duration",
    amc: "ICICI",
    benchmark: "CRISIL Short Duration Index",
    popularityRank: 42,
  },
  {
    fundName: "HDFC Short Term Debt Fund",
    assetType: "Debt",
    category: "Short Duration",
    amc: "HDFC",
    benchmark: "CRISIL Short Duration Index",
    popularityRank: 43,
  },
  {
    fundName: "Kotak Bond Fund",
    assetType: "Debt",
    category: "Medium Duration",
    amc: "Kotak",
    benchmark: "CRISIL Medium Duration Index",
    popularityRank: 44,
  },
  {
    fundName: "Nippon India Strategic Debt Fund",
    assetType: "Debt",
    category: "Dynamic Bond",
    amc: "Nippon",
    benchmark: "CRISIL Dynamic Bond Index",
    popularityRank: 45,
  },

  {
    fundName: "SBI Gold Fund",
    assetType: "Gold",
    category: "Gold",
    amc: "SBI",
    benchmark: "Domestic Gold Price",
    popularityRank: 46,
  },
  {
    fundName: "HDFC Gold Fund",
    assetType: "Gold",
    category: "Gold",
    amc: "HDFC",
    benchmark: "Domestic Gold Price",
    popularityRank: 47,
  },
  {
    fundName: "ICICI Prudential Gold Fund",
    assetType: "Gold",
    category: "Gold",
    amc: "ICICI",
    benchmark: "Domestic Gold Price",
    popularityRank: 48,
  },
  {
    fundName: "Axis Gold Fund",
    assetType: "Gold",
    category: "Gold",
    amc: "Axis",
    benchmark: "Domestic Gold Price",
    popularityRank: 49,
  },
  {
    fundName: "Nippon India Gold Savings Fund",
    assetType: "Gold",
    category: "Gold",
    amc: "Nippon",
    benchmark: "Domestic Gold Price",
    popularityRank: 50,
  },
];

export default fundReferenceSeedData;
